article/urls.py
from django.contrib import admin
from django.urls import path
from article import views

app_name="article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('comment/<int:id>',views.comment,name="comment"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.update,name="update"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('',views.articles,name="article")
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include

from article import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('hakkımızda/',views.hakkımızda,name="hakkımızda"),
    path('articles/',include("article.urls"),name="articles"),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models

from ckeditor.fields import RichTextField


# Create your models here.

class Article(models.Model):
    author=models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar")
    title=models.CharField(max_length=50,verbose_name="Başlık")
    content=RichTextField()
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Tarih")
    article_image=models.FileField(blank=True,null=True,verbose_name="Makaleye Fotoğraf Ekleyin")

    class Meta():
        ordering=["-created_date"]

    # def __str__(self):
    #     return self.title  böylede sadece title gözükür ama adminde oluşturulan sınıf ile daha verimli 
    # newUser(username="sdhjasd")
    # newUser.set_password(132) bu şifreyi gizler 
    #


class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE,related_name="comments")
    comment_author=models.CharField(max_length=50,verbose_name="isim")
    comment_content=models.CharField(max_length=200,verbose_name="yorum")
    comment_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta():
        ordering=["-comment_date"]

article/forms.py
from django import forms

from .models import Article

class AddartilceForm(forms.ModelForm):
    class Meta():
        model=Article
        fields=["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from .models import Article,Comment
from .forms import AddartilceForm
# Create your views here.

from django.contrib import messages

def index(request):
    context={
        "ad":"TAYFUN",
        "soyad":"KAYA",
        "bilgiler":["Fenerbahçeli","Birisi..."]
    }
    return render(request,"index.html",context)

def hakkımızda(request):
    return render(request,"hakkımızda.html")

# Makale gösterme sayfası

def articles(request):

    keyword=request.GET.get("keyword")
    if keyword:
        articles=Article.objects.filter(title__contains=keyword)
        return render(request,"articles.html",{"articles":articles})
    articles=Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

# **********

@login_required(login_url="user:login")
def dashboard(request):

    articles=Article.objects.filter(author=request.user)
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)


@login_required(login_url="user:login")
def addarticle(request):
    form=AddartilceForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Makale Başarıyla eklendi")
        return redirect("article:dashboard")
    context={
        "form":form
    }
    return render(request,"addarticle.html",context)


@login_required(login_url="user:login")
def detail(request,id):
    #article=Article.objects.filter(id=id).first()
    article=get_object_or_404(Article,id=id)

    comments=article.comments.all()


    return render(request,"detail.html",{"article":article,"comments":comments})


@login_required(login_url="user:login")
def update(request,id):
    article=get_object_or_404(Article,id=id)

    form=AddartilceForm(request.POST or None,request.FILES or None,instance=article )

    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Makale Başarıyla güncellendi")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})


@login_required(login_url="user:login")
def delete(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi")
    return redirect("article:dashboard")


@login_required(login_url="user:login")
def comment(request,id):
    article=get_object_or_404(Article,id=id)

    if request.method=="POST":
        comment_author=request.POST.get("comment-author")
        comment_content=request.POST.get("comment_content")
        newComment=Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article=article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/addarticle.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block title %}
Makale Ekle
{% endblock title %}



{% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Ekle</h3>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Ekle</button>
    </form>
  </div>
</div>

{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}


{% block title %}
Makaleler
{% endblock title %}



{% block body %}


{% if articles %}
<div class="row">
    
    <div class="col-md-10 offset-md-2">
        
        <div class="col-lg-8">
            <h2>Makaleler</h2>
            <hr>
            
            <form action="">
                {% csrf_token %}
                <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Search" style="border: 1px solid rgba(0, 0, 255, 0.68);">
                <button type="submit" class="btn btn-primary btn-sm">Search</button>
            </form>
                   
            
            {% for article in articles %}
            
                <!-- Title -->
                <a href="{% url 'article:detail' article.id %}" style="text-decoration: none;color: black;"><h1 class="mt-4">{{article.title}}</h1></a>

                <!-- Author -->
                <p class="lead">
                    <p><small>Yazar: </small>{{article.author.username}}</p>
                </p>

                <hr>

                <!-- Date/Time -->
                <p>{{article.created_date}}</p>

                <hr>

                {% if article.article_image %}
                    <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}"></a> 
                {% endif %}
                        
                <p>{{article.content | safe | truncatewords:40}}</p>

                <a style="float: right;" href="{% url 'article:detail' article.id %}" class="btn btn-primary">Devamını Oku</a> 
                <hr style="background-color: rgba(0, 13, 255, 0.659);"> 
                <br>
                
            {% endfor %}
        </div>
    </div>
</div>
    

{% else %}
<div class="col-md-10 offset-md-2">
        
    <div class="col-lg-8">
        <hr>
        <div class="alert alert-danger">Herhangi bir makale bulunamadı</div>
    </div>
</div>

{% endif %}


{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}

{% block title %}
Dashboard
{% endblock title %}


{% block body %}
    <h3>Dashboard</h3>
    <br>
    <small>Hoşgeldiniz {{request.user.username}}</small>
    <hr>
    {% if articles %}
        <table class="table">
            <thead>
                <tr>
                <th scope="col">id</th>
                <th scope="col">Başlık</th>
                <th scope="col">Yazar</th>
                <th scope="col">Tarih</th>
                <th scope="col">Güncelle</th>
                <th scope="col">Sil</th>
                </tr>
            </thead>
            <tbody>
        
                {% for article in articles %}
                    <tr>
                        <th scope="row">{{article.id}}</th>
                        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                        <td>{{article.author.username}}</td>
                        <td>{{article.created_date}}</td>
                        <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
                        <td><a href="{% url 'article:update' article.id %}" class="btn btn-success">Güncelle</a></td>
                    </tr>
                {% endfor %}
        
        
                
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-success">Makaleniz Bulunmamaktadır</div>
    {% endif %}
    
    
    <hr>
<a href="{% url 'article:addarticle'%}" class="btn btn-primary">Makale Ekle</a>
<br><br><br><br><br>
{% endblock body %}

templates/detail.html
{% extends 'layout.html' %}



{% block title %}
Makale Detay
{% endblock title %}

{% block body %}
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-9">

        <!-- Title -->
        <h1 class="mt-4">{{article.title}}</h1>

        <!-- Author -->
        <p class="lead">
          <p><small>Yazar: </small>{{article.author.username}}</p>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        {% if article.article_image %}
          <img class="img-fluid rounded" src="{{article.article_image.url}}"> 
        {% endif %}
        

        
        <p>{{article.content | safe}}</p>




        <hr>     
        
           
        <div class="card my-4">
          {% if comments %}
            {% for comment in comments %}
            <div style="padding: 3px;">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">{{comment.comment_author}} <small>{{comment.comment_date}}</small></h5>
                  {{comment.comment_content}}
              </div>
            {% endfor %}
          {% endif %}
          <hr>
          <h5 class="card-header">Yorum:</h5>
          <div class="card-body">
            <form action="{% url 'article:comment' article.id %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                <label>İsminiz</label>
                  <input name="comment-author" class="form-control" placeholder="İsminizi giriniz">
                    
              </div>
              <div class="form-group">
                <label >Yorum</label>
                <textarea name="comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Gönder</button>
            </form>
          </div>
        </div>
      </div>
      
    </div>
    
{% endblock body %}

templates/hakkımızda.html
{% extends 'layout.html' %}

{% block title %}
hakkımızda
{% endblock title %}



{% block body %}
  <div style="background: rgb(4, 95, 253);" class="jumbotron text-center">
      <h2 style="color: rgb(255, 255, 255);">Hakkımızda</h2>
  </div>
  
{% endblock body %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
  Anasayfa
{% endblock title %}
Anasayfa
{% block body %}
    <div class="jumbotron text-center">
        <h2>Hoşgeldiniz</h2>
        <small>Merhaba {{ad}} 
          {% if soyad %}
            {{soyad}}
          {% endif %}
        </small>
        <br>
        
          {% for veri in bilgiler %}
            <small>{{veri}}</small>
          {% endfor %}
        <br>
        {% if request.user.is_authenticated %}
          <p>GİRİŞ YAPILDI :{{request.user.username}}</p>
        {% else %}
          <p>GİRİŞ YAPILMADI</p>
        {% endif %}
    </div>
    <br><br><br><br><br><br><br><br><br><br>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>
        {% block title %}
          
        {% endblock title %}
    </title>
</head>
<body>
    {% include "includes/navbar.html" %}

    

    <div style="margin-top: 100px;margin-bottom: 100px " class="container">

    
        {% if messages %}
    
            {% for message in messages %}
                {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}
            {% endfor %}

        {% endif %}


        {% block body %}

        
        {% endblock body %}
        
        
    </div>


    
        
        


    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block title %}
Giris Yapınız
{% endblock title %}

{% block body %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Giriş Yap</h3>
    <br>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Kayıt Ol</button>
    </form>
  </div>
</div>

<br><br><br><br><br><br><br><br><br><br>


{% endblock body %}

templates/logout.html
{% extends 'layout.html' %}


{% block title %}
Çıkış Yapılıyor
{% endblock title %}


{% block body %}
<div class="alert alert-danger">Çıkış yapılıyor</div>
{% endblock body %}

templates/register.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block title %}
Kayıt Ol
{% endblock title %}



{% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Kayıt Ol</h3>
    <br>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Kayıt Ol</button>
    </form>
  </div>
</div>
<br><br><br><br><br><br><br>
{% endblock body %}

templates/update.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block title %}
Makale Ekle
{% endblock title %}



{% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Makale Güncelle</h3>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Güncelle</button>
    </form>
  </div>
</div>

{% endblock body %}